### ISSUE TITLE
is there a way to skip some notebooks in the test suite?

### ISSUE THREAD

**Issue by kosack** [escape2020/school2022#40]
In the debugging lecture, I have a notebook with some cells that *should* fail, since there are bugs.  But that now causes the CI to fail as well.

**Comment by maxnoe** [comment]
You could replace the `**/*.ipynb` with a different pattern / manual list of notebooks to be tested.

**Comment by vuillaut** [comment]
> In the debugging lecture, I have a notebook with some cells that _should_ fail, since there are bugs. But that now causes the CI to fail as well.

Ha yes of course it's and intended error 😅

You can ignore a single cell in your notebook by editing its metadata:

https://github.com/treebeardtech/nbmake

**Comment by kosack** [comment]
thanks! fixed in #42 and #39
